apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1alpha
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              message:
                type: string
              replicas:
                type: integer
            required:
              - message
    additionalPrinterColumns:
      - jsonPath: .spec.message
        name: message
        type: string
        description: message content which wan to show
      - name: AGE
        type: date
        jsonPath: .metadata.creationTimestamp
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath:  .status.replicas
        labelSelectorPath: .status.labelSelector
  scope: Namespaced
  names:
    kind: Sample
    plural: samples
    singular: sample
    shortNames: ["sp"]